### ISSUE TITLE
Missing toplove.cmake

### ISSUE THREAD

**Issue by FriedCircuits** [vmayoral/beagle-ros#1]
When running catking_make, it can not find toplevel.cmake. My export for ROS is

beaglebone:~/catkin_ws# export | grep ROS
declare -x ROS_DISTRO="hydro"
declare -x ROS_MASTER_URI="http://beaglebone:11311"
declare -x ROS_PACKAGE_PATH="/home/root/catkin_ws/src:/usr/share"
declare -x ROS_ROOT="/usr/share/ros"
declare -x ROS_WORKSPACE="/usr"

Running catkin_make 
beaglebone:~/catkin_ws# catkin_make
Base path: /home/root/catkin_ws
Source space: /home/root/catkin_ws/src
Build space: /home/root/catkin_ws/build
Devel space: /home/root/catkin_ws/devel
Install space: /home/root/catkin_ws/install
Creating the toplevel cmake file failed: Could neither find file "toplevel.cmake" in any workspace nor relative, checked the following paths:
/home/root/catkin_ws/src/catkin/cmake/toplevel.cmake
/usr/catkin/cmake/toplevel.cmake
/usr/lib/python2.7/cmake/toplevel.cmake
/usr/share/catkin/cmake/toplevel.cmake
/usr/lib/share/catkin/cmake/toplevel.cmake

**Comment by vmayoral** [comment]
Your setup looks fine however compiling ROS packages on the target is not available yet (discussed [here](https://github.com/bmwcarit/meta-ros/issues/103)).

For now you can cross-compile your packages setting up an Ångström build environment ([instructions](http://www.angstrom-distribution.org/building-angstrom)), create a recipe for your ROS package (this [script](https://github.com/bmwcarit/meta-ros/blob/master/scripts/create-recipe.py) helps with that) and bitbake the recipe.

**Comment by FriedCircuits** [comment]
Thanks, makes sense. I guess that didn't occur to me. I am just getting started with ROS and a possible platform instead of making something from scratch. My first goal is to get a webcam working. Its working with mjpg-streamer.  
I take it I need to cross-compile the usb_cam drivers?

Thanks

**Comment by vmayoral** [comment]
Not sure about that. A quick look at the [Angstrom feed](http://www.angstrom-distribution.org/repo/) and the [OpenEmbedded layer index](http://layers.openembedded.org/layerindex/branch/master/recipes/) doesn't show any result so you might have to create the recipes.

You could also take a quick look at previous work with [webcams on Angstrom](https://www.google.es/search?q=angstrom+webcam&oq=angstrom+webcam&aqs=chrome..69i57.2590j0j7&sourceid=chrome&espvd=210&es_sm=91&ie=UTF-8). It seems a lot of people made it work so it could be of some help ;).

Regards,
