### ISSUE TITLE
Remove all recipes that have been added to meta-ros from the beagle-ros repository 

### ISSUE THREAD

**Issue by bulwahn** [vmayoral/beagle-ros#2]
The ros-control recipes and some others have been added to the meta-ros layer.
To avoid that the recipes in beagle-ros and meta-ros diverge, the recipes in beagle-ros should be removed and they should be to developed further in the meta-ros layer. You can experiment with your fork of meta-ros and provide pull requests whenever your changes have stabilized. I am sure that the review of the future changes will be simpler than the review of the initial contribution.

**Comment by vmayoral** [comment]
Thanks Lukas. https://github.com/vmayoral/beagle-ros/commit/539582952505b742ea08bb99563d15d12a8b27bc does that.

There're some recipes that are still not merged into the meta-ros layer (e.g. [turtle-actionlib_0.1.7.bb](https://github.com/vmayoral/beagle-ros/blob/master/recipes-ros/common-tutorials/turtle-actionlib_0.1.7.bb)) that will be kept here.
