### ISSUE TITLE
Remove more recipes that have been added to meta-ros

### ISSUE THREAD

**Issue by bulwahn** [vmayoral/beagle-ros#4]
The following recipes have been added to the meta-ros layer and are maintained there. They can be removed from this add-on layer.
- shape-tools
- robot-model
- random-numbers
- python-orocos-kdl
- orocos-kdl
- octomap
- libqhull
- geometric-shapes
- eigen-stl-containers
- assimp

This is a continuation of #2.

**Comment by vmayoral** [comment]
aae5a5bf490517f764ba54c4f3ed1b10868d4280 does it.  :+1:
