### ISSUE TITLE
Fix FILESPATH for linux-mpu9150

### ISSUE THREAD

**Issue by ghost** [vmayoral/beagle-ros#6]
Dear Vmayoral,

I was building Angstrom/core-image-roscore.
I received warning about patch of linux-mpu9150 can not be found.
I then also struggled with error while building.
I think I may fix the error please kindly check my patch attached.

Thank you very much.
Best regards,
Huy Hoang
[fix_linux-mpu9150.zip](https://github.com/vmayoral/beagle-ros/files/303940/fix_linux-mpu9150.zip)

**Comment by vmayoral** [comment]
Hi @huyht1205,

I'm currently not supporting anymore beagle-ros.
Regards,
